CREATE TABLE userInfo (firstName varchar(30) NOT NULL,
                       lastName varchar(30) NOT NULL,
                       username VARCHAR(30) NOT NULL ,
                       password VARCHAR(30) NOT NULL , 
                       email VARCHAR(320) NOT NULL , 
                       birthday VARCHAR(30) NOT NULL, 
                       strAddress    VARCHAR(100) NOT NULL,
                       city        VARCHAR(100) NOT NULL,
                       state       VARCHAR(2) NOT NULL,
                       zip VARCHAR(5) NOT NULL,
                       userType VARCHAR(1) NOT NULL,
                       promotion INT(11) DEFAULT NULL,
                       verification INT(11) DEFAULT NULL,
                       email_verified_at DATETIME NULL,
                       verified INT NOT NULL,
                       PRIMARY KEY (username));