CREATE TABLE userInfo (firstName varchar(10) NOT NULL UNIQUE,
                       lastName varchar(15) NOT NULL,
                       username VARCHAR(30) NOT NULL ,
                       password VARCHAR(30) NOT NULL , 
                       email VARCHAR(320) NOT NULL , 
                       birthday DATE NOT NULL, 
                       strAddress    VARCHAR(120),
                       city        VARCHAR(100) NOT NULL,
                       state       CHAR(2) NOT NULL,
                       zip  VARCHAR(16) NOT NULL,
                       userType VARCHAR(16) NOT NULL,
                       promotion INT(20) NOT NULL,
                       verification_code INT(20) NOT NULL,
                       email_verified_at DATETIME NULL,
                       verified INT NOT NULL,
                       PRIMARY KEY (username));